CREATE TABLE MOVIE_COUNTRIES(
    MOVIEID VARCHAR2(50),
    COUNTRY VARCHAR2(100)
);

CREATE TABLE MOVIE_LOCATIONS( 
    MOVIEID VARCHAR2(50), 
    LOCATION VARCHAR2(100)
);

CREATE TABLE MOVIE_GENRES(
    MOVIEID VARCHAR2(50),
    GENRE VARCHAR2(100)
);

CREATE TABLE MOVIE_TAGS(
    MOVIEID VARCHAR2(50),
    TAGID VARCHAR2(100),
    TAGWEIGHT INTEGER
);

CREATE TABLE MOVIE(
    MOVIEID VARCHAR2(50) PRIMARY KEY,
    TITLE VARCHAR2(200),
    MYEAR INTEGER,
    RTALLCRITICSRATING NUMBER,
    RTALLCRITICSNUMREVIEWS NUMBER,
    RTTOPCRITICRATING NUMBER,
    RTTOPCRICTICNUMREVIEWS NUMBER,
    RTAUDIENCERATING NUMBER,
    RTAUDIENCENUMRATING NUMBER
);

CREATE TABLE TAGS(
    TAGID VARCHAR2(50) PRIMARY KEY,
    VALUE VARCHAR2(200)
);

CREATE TABLE USER_TAGGEDMOVIES(
    USERID VARCHAR2(50),
    MOVIEID VARCHAR2(50),
    TAGID VARCHAR2(100),
    DATE_DAY INTEGER,
    DATE_MONTH INTEGER,
    DATE_YEAR INTEGER,
    DATE_HOUR INTEGER,
    DATE_MINUTE INTEGER,
    DATE_SECOND INTEGER
);

CREATE INDEX INDMOVIEID ON MOVIE(MOVIEID);
CREATE INDEX INDGENRE ON MOVIE_GENRES(GENRE);
CREATE INDEX INDCOUNTRY ON MOVIE_COUNTRIES(COUNTRY);
CREATE INDEX INDTAG ON TAGS(TAGID);
CREATE INDEX INDUSER ON USER_TAGGEDMOVIES(USERID);
CREATE INDEX INDLOCATION ON MOVIE_LOCATIONS(LOCATION);
